[theme]
primaryColor = "#00ff41"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#fafafa"
font = "sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false